name: Conditional Workflow

on:
  push:
    branches: [ main ]

jobs:
  if: contains(join(github.event.commits.*.message, ' '), 'build')
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug commit messages
        run: |
          echo "commit message=${{ join(github.event.commits.*.message, ' ') }}"
          echo "contains build=${{ contains(join(github.event.commits.*.message, ' '), 'build') }}"
