name: Conditional Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    if: >
      contains(
        join(github.event.commits.*.message, ' '),
        '[build]'
      )
    runs-on: ubuntu-latest

    steps:
      - run: echo "Tests triggered"
             $containsBuild = contains(
              join(github.event.commits.*.message, ' '),
              '[build]'
              )
             $commitMessage = join(github.event.commits.*.message, ' ')
             echo "contains Build=$containsBuild"
             echo "commit message=$commitMessage"
